import { installCloudRunCors } from './server/installCloudRunCors';
import { installOpenAIImageRetry } from './server/installOpenAIImageRetry';
import { installGeneratedMediaFetchCompat } from './server/generatedMediaFetchCompat';
import { installBackgroundGenerationPersistence } from './server/backgroundGenerationPersistence';
import { installMediaDownload } from './server/installMediaDownload';
import { installMarketCashPaymentProxy } from './server/marketCashPaymentProxy';
import { installMobileMoneyLivePaymentProxy } from './server/mobileMoneyLivePaymentProxy';
import { installMpesaLiveCallback } from './server/mpesaLiveCallback';
import { installMarketCashBilling } from './server/installMarketCashBilling';
import { installLaunchPricingSync } from './server/installLaunchPricing';
import { installProviderWalletAdminApi } from './server/installProviderWalletAdmin';
import { installHostingSelfDeploy } from './server/hostingSelfDeploy';
import { installVideoEntitlements } from './server/installVideoEntitlements';
import { installDeviceBinding } from './server/installDeviceBinding';

installCloudRunCors();
installOpenAIImageRetry();
installGeneratedMediaFetchCompat();
installBackgroundGenerationPersistence();
installProviderWalletAdminApi();
installMediaDownload();
installMarketCashPaymentProxy();
installMobileMoneyLivePaymentProxy();
installMpesaLiveCallback();
installMarketCashBilling();
installLaunchPricingSync();
installHostingSelfDeploy();
installVideoEntitlements();
installDeviceBinding();
void import('./server');
