import { installGeneratedMediaFetchCompat } from './server/generatedMediaFetchCompat';
import { installBackgroundGenerationPersistence } from './server/backgroundGenerationPersistence';
import { installMediaDownload } from './server/installMediaDownload';
import { installMarketCashPaymentProxy } from './server/marketCashPaymentProxy';
import { installMobileMoneyLivePaymentProxy } from './server/mobileMoneyLivePaymentProxy';
import { installMpesaLiveCallback } from './server/mpesaLiveCallback';
import { installMarketCashBilling } from './server/installMarketCashBilling';
import { installLaunchPricingSync } from './server/installLaunchPricing';
import { installProviderWalletAdminApi } from './server/installProviderWalletAdmin';

installGeneratedMediaFetchCompat();
installBackgroundGenerationPersistence();
installProviderWalletAdminApi();
installMediaDownload();
installMarketCashPaymentProxy();
installMobileMoneyLivePaymentProxy();
installMpesaLiveCallback();
installMarketCashBilling();
installLaunchPricingSync();
void import('./server');