import { randomUUID } from 'node:crypto';
import express from 'express';
import { adminAuth, adminDb } from './firebaseAdmin';
import { ANNUAL_DISCOUNT_PERCENT, LAUNCH_CREDIT_PACKS, LAUNCH_SUBSCRIPTION_PLANS, PRICING_VERSION } from '../src/config/commercialPricing';
import { getMpesaLivePublicStatus, isMpesaLiveConfigured, mpesaLiveMessage, normalizeMpesaLiveMsisdn, requestMpesaLiveC2B } from './mpesaLiveClient';

const INSTALL_FLAG = Symbol.for('mungwele.mobileMoneyLivePaymentProxyInstalled');
const APP_FLAG = Symbol.for('mungwele.mobileMoneyLiveRoutesMounted');
type Provider = 'mpesa' | 'airtel' | 'orange' | 'afrimoney';
type TargetKind = 'subscription' | 'credits';
type BillingCycle = 'monthly' | 'yearly';
type ResolvedTarget = { kind: TargetKind; targetId: string; label: string; amountUsd: number; creditsAdded: number; planId?: 'creator'|'pro'|'studio'; billingCycle?: BillingCycle };
const clean=(v:unknown,max=120)=>String(v??'').trim().slice(0,max);const money=(v:number)=>Math.round(v*100)/100;
const DEFAULT_PRICING={annualDiscountPercent:ANNUAL_DISCOUNT_PERCENT,creditPacks:LAUNCH_CREDIT_PACKS.map(x=>({...x})),subscriptionPlans:LAUNCH_SUBSCRIPTION_PLANS.map(x=>({...x,features:[...x.features]}))};
function fail(message:string,status=400,code='MOBILE_MONEY_REQUEST_INVALID'){return Object.assign(new Error(message),{status,code});}
function normalizeAttemptId(value:unknown){const id=clean(value,72).replace(/[^a-zA-Z0-9_-]/g,'');if(!id)return randomUUID();if(id.length<8)throw fail('Identifiant de tentative invalide.',400,'PAYMENT_ATTEMPT_INVALID');return id;}
function normalizeMsisdn(value:unknown){const digits=String(value||'').replace(/\D/g,'');if(digits.length<9||digits.length>15)throw fail('Numéro Mobile Money invalide.',400,'MSISDN_INVALID');return digits.startsWith('243')?digits:`243${digits.replace(/^0/,'')}`;}
async function requireUser(req:express.Request){const header=String(req.headers.authorization||'');if(!header.startsWith('Bearer '))throw fail('Connexion requise pour payer.',401,'AUTH_REQUIRED');try{const d=await adminAuth.verifyIdToken(header.slice(7).trim());return{uid:d.uid,email:String(d.email||'')}}catch{throw fail('Session Firebase invalide ou expirée.',401,'AUTH_INVALID')}}
async function loadPricing(){try{const snap=await adminDb.doc('appSettings/pricing').get();const d:any=snap.data()||{};if(Number(d.pricingVersion)!==PRICING_VERSION)return DEFAULT_PRICING;return{annualDiscountPercent:Number.isFinite(Number(d.annualDiscountPercent))?Number(d.annualDiscountPercent):DEFAULT_PRICING.annualDiscountPercent,creditPacks:Array.isArray(d.creditPacks)&&d.creditPacks.length?d.creditPacks:DEFAULT_PRICING.creditPacks,subscriptionPlans:Array.isArray(d.subscriptionPlans)&&d.subscriptionPlans.length?d.subscriptionPlans:DEFAULT_PRICING.subscriptionPlans}}catch{return DEFAULT_PRICING}}
async function resolveTarget(target:any):Promise<ResolvedTarget>{if(!target?.kind)throw fail('Achat MUNGWELE invalide.',400,'TARGET_REQUIRED');const p=await loadPricing();const meta=target.metadata||{};if(target.kind==='credits'){const id=clean(meta.packId,80);const pack:any=p.creditPacks.find((x:any)=>String(x.id)===id&&x.enabled!==false);if(!pack)throw fail('Pack de crédits introuvable.',400,'CREDIT_PACK_INVALID');const credits=Math.max(0,Math.floor(Number(pack.credits||0)));const amountUsd=money(Number(pack.priceUsd||0));if(!credits||!amountUsd)throw fail('Configuration du pack invalide.',500);return{kind:'credits',targetId:id,label:`${credits} crédits MUNGWELE`,amountUsd,creditsAdded:credits}}const planId=clean(meta.planId,40)as'Reator'|'creator'|'pro'|'studio';const actualPlanId=(planId==='creator'||planId==='pro'||planId==='studio'?planId:'')as'creator'|'pro'|'studio';const cycle:BillingCycle=String(meta.billingCycle||'monthly')==='yearly'?'yearly':'monthly';const plan:any=p.subscriptionPlans.find((x:any)=>String(x.id)===actualPlanId&&String(x.id)!=='free');if(!plan)throw fail('Abonnement introuvable.',400,'SUBSCRIPTION_PLAN_INVALID');const monthly=money(Number(plan.priceMonth||0));const monthlyCredits=Math.max(0,Math.floor(Number(plan.creditsMonthly||0)));const discount=Math.max(0,Math.min(80,Number(p.annualDiscountPercent||0)));const amountUsd=cycle==='yearly'?money(monthly*12*(1-discount/100)):monthly;return{kind:'subscription',targetId:actualPlanId,planId:actualPlanId,billingCycle:cycle,label:`Abonnement ${String(plan.name||actualPlanId)} ${cycle==='yearly'?'annuel':'mensuel'}`,amountUsd,creditsAdded:cycle==='yearly'?monthlyCredits*12:monthlyCredits}}
const fingerprint=(t:ResolvedTarget)=>[t.kind,t.targetId,t.billingCycle||'',t.amountUsd,t.creditsAdded].join('|');

const genericConfigs:Record<Exclude<Provider,'mpesa'>,{label:string,key:string,url:string,merchant:string}>={
  airtel:{label:'Airtel Money',key:'AIRTEL_MONEY_API_KEY',url:'AIRTEL_MONEY_API_URL',merchant:'AIRTEL_MONEY_MERCHANT_ID'},
  orange:{label:'Orange Money',key:'ORANGE_MONEY_API_KEY',url:'ORANGE_MONEY_API_URL',merchant:'ORANGE_MONEY_MERCHANT_ID'},
  afrimoney:{label:'Afrimoney',key:'AFRIMONEY_API_KEY',url:'AFRIMONEY_API_URL',merchant:'AFRIMONEY_MERCHANT_ID'},
};
function genericConfigured(provider:Exclude<Provider,'mpesa'>){const c=genericConfigs[provider];return Boolean(process.env[c.key]&&process.env[c.url]);}
function providerConfigured(provider:Provider){return provider==='mpesa'?isMpesaLiveConfigured():genericConfigured(provider);}

async function prepareIntent(id:string,uid:string,target:ResolvedTarget,msisdn:string,provider:Provider){const ref=adminDb.collection('mobileMoneyPaymentIntents').doc(id);let existing:any=null;await adminDb.runTransaction(async tx=>{const snap=await tx.get(ref);if(snap.exists){const d:any=snap.data()||{};if(String(d.userId||'')!==uid||String(d.targetFingerprint||'')!==fingerprint(target)||String(d.provider||'')!==provider)throw fail('Cette tentative appartient à un autre achat.',409,'PAYMENT_ATTEMPT_CONFLICT');if(d.status==='settled'&&d.result)existing=d.result;return;}tx.create(ref,{id,userId:uid,provider,environment:'production',targetKind:target.kind,targetId:target.targetId,targetFingerprint:fingerprint(target),amountUsd:target.amountUsd,creditsExpected:target.creditsAdded,msisdnMasked:`${'*'.repeat(Math.max(0,msisdn.length-4))}${msisdn.slice(-4)}`,status:'pending',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})});return{ref,existing};}

async function settlePurchase(id:string,uid:string,target:ResolvedTarget,provider:Provider,payload:any){const settlementRef=adminDb.collection('mobileMoneySettlements').doc(id);const intentRef=adminDb.collection('mobileMoneyPaymentIntents').doc(id);const userRef=adminDb.collection('users').doc(uid);const txRef=adminDb.collection('creditTransactions').doc(`mobile-money-${provider}-${id}`);let result:any=null;await adminDb.runTransaction(async tx=>{const[settled,userSnap]=await Promise.all([tx.get(settlementRef),tx.get(userRef)]);if(settled.exists){result=settled.data()?.result||null;return}if(!userSnap.exists)throw fail('Profil MUNGWELE introuvable.',404,'USER_NOT_FOUND');const user:any=userSnap.data()||{};const balanceAfter=Math.max(0,Number(user.credits||0))+target.creditsAdded;const now=new Date(),nowIso=now.toISOString();const updates:any={credits:balanceAfter,updatedAt:nowIso};let plan:string|undefined,subscriptionEndsAt:string|undefined;if(target.kind==='subscription'&&target.planId){plan=target.planId;const end=new Date(now);if(target.billingCycle==='yearly')end.setUTCFullYear(end.getUTCFullYear()+1);else end.setUTCMonth(end.getUTCMonth()+1);subscriptionEndsAt=end.toISOString();Object.assign(updates,{plan,subscriptionCycle:target.billingCycle,subscriptionStartedAt:nowIso,subscriptionEndsAt,subscriptionSource:`mobile-money-${provider}`})}const transactionId=clean(payload?.output_TransactionID||payload?.transactionId||payload?.transaction_id||payload?.id||payload?.reference,120);const conversationId=clean(payload?.output_ConversationID||payload?.conversationId||payload?.conversation_id,120);result={success:true,status:'settled',provider,environment:'production',transactionId,conversationId,amountUsd:target.amountUsd,creditsAdded:target.creditsAdded,balanceAfter,plan,billingCycle:target.billingCycle,subscriptionEndsAt,message:target.kind==='credits'?`${target.creditsAdded} crédits ont été ajoutés.`:`${target.label} activé.`};tx.update(userRef,updates);tx.set(txRef,{userId:uid,amount:target.creditsAdded,type:'purchase',description:`${target.label} via ${provider}`,balanceAfter,source:`mobile-money-${provider}`,providerTransactionId:transactionId||null,amountPaidUsd:target.amountUsd,pricingVersion:PRICING_VERSION,createdAt:nowIso});tx.set(settlementRef,{id,userId:uid,provider,environment:'production',status:'settled',targetKind:target.kind,targetId:target.targetId,amountUsd:target.amountUsd,creditsAdded:target.creditsAdded,pricingVersion:PRICING_VERSION,result,createdAt:nowIso,updatedAt:nowIso});tx.set(intentRef,{status:'settled',result,updatedAt:nowIso},{merge:true})});if(!result)throw fail('Paiement confirmé mais synchronisation MUNGWELE incomplète.',500,'SETTLEMENT_PENDING');return result;}

function genericState(payload:any){const raw=clean(payload?.status||payload?.paymentStatus||payload?.transactionStatus||payload?.state||payload?.result,40).toLowerCase();if(['success','successful','settled','completed','paid'].includes(raw)||payload?.success===true&&Boolean(payload?.transactionId||payload?.reference||payload?.id))return'settled';if(['pending','processing','initiated','queued','waiting'].includes(raw)||payload?.pending===true)return'pending';return'failed';}
async function genericRequest(provider:Exclude<Provider,'mpesa'>,input:{target:ResolvedTarget;msisdn:string;attemptId:string}){const c=genericConfigs[provider];const url=String(process.env[c.url]||'').trim(),key=String(process.env[c.key]||'').trim();if(!url||!key)throw fail(`API ${c.label} absente.`,503,`${provider.toUpperCase()}_NOT_CONFIGURED`);const response=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json','X-Merchant-Id':String(process.env[c.merchant]||'')},body:JSON.stringify({amount:input.target.amountUsd,currency:'USD',msisdn:input.msisdn,reference:input.attemptId,description:input.target.label,metadata:{source:'MUNGWELE_IA',targetKind:input.target.kind,targetId:input.target.targetId}})});const payload:any=await response.json().catch(()=>({}));return{response,payload,state:genericState(payload)}}

async function paymentHandler(req:express.Request,res:express.Response){const requested=clean(req.params.provider,30).toLowerCase()as Provider;const allowed:Provider[]=['mpesa','airtel','orange','afrimoney'];if(!allowed.includes(requested))return res.status(404).json({error:'Réseau Mobile Money inconnu.'});try{const user=await requireUser(req);if(!providerConfigured(requested))throw fail(`API ${requested==='mpesa'?'M-Pesa':genericConfigs[requested as Exclude<Provider,'mpesa'>].label} absente.`,503,'PROVIDER_NOT_CONFIGURED');const target=await resolveTarget(req.body?.target||{});const expected=Number(req.body?.target?.amountUsd);if(Number.isFinite(expected)&&Math.abs(money(expected)-target.amountUsd)>.009)throw fail('Le prix affiché a changé. Rechargez la page.',409,'PRICE_CHANGED');const msisdn=requested==='mpesa'?normalizeMpesaLiveMsisdn(req.body?.msisdn):normalizeMsisdn(req.body?.msisdn);const id=normalizeAttemptId(req.body?.attemptId);const intent=await prepareIntent(id,user.uid,target,msisdn,requested);if(intent.existing)return res.json(intent.existing);
  if(requested==='mpesa'){const seed=id.replace(/[^a-zA-Z0-9]/g,'');const{response,payload}=await requestMpesaLiveC2B({amountUsd:target.amountUsd,msisdn,thirdPartyConversationId:`MIA${seed}`.slice(0,40),transactionReference:`MIA${Date.now().toString(36)}${seed.slice(-6)}`.slice(0,20),purchasedItemsDescription:clean(target.label.replace(/[^a-zA-Z0-9 À-ÿ._-]/g,''),120)||'MUNGWELE'});const code=clean(payload?.output_ResponseCode,32),desc=clean(payload?.output_ResponseDesc,300);if(response.ok&&code==='INS-0'){if(clean(payload?.output_TransactionID,120))return res.json(await settlePurchase(id,user.uid,target,requested,payload));await intent.ref.set({status:'pending',responseCode:code,responseDesc:desc,updatedAt:new Date().toISOString()},{merge:true});return res.status(202).json({success:true,status:'pending',provider:requested,message:desc||'Confirmation en attente.'})}throw fail(mpesaLiveMessage(code,desc),response.status>=400?response.status:402,'MPESA_PAYMENT_FAILED');}
  const generic=await genericRequest(requested,target?{target,msisdn,attemptId:id}:never);if(generic.response.ok&&generic.state==='settled')return res.json(await settlePurchase(id,user.uid,target,requested,generic.payload));if(generic.response.ok&&generic.state==='pending'){await intent.ref.set({status:'pending',providerPayload:generic.payload,updatedAt:new Date().toISOString()},{merge:true});return res.status(202).json({success:true,status:'pending',provider:requested,message:clean(generic.payload?.message||generic.payload?.description,240)||'Confirmation en attente.'})}throw fail(clean(generic.payload?.message||generic.payload?.error,240)||'Paiement refusé.',generic.response.status>=400?generic.response.status:402,'MOBILE_MONEY_PAYMENT_FAILED');
}catch(error:any){const status=Number(error?.status||500);console.warn('[MUNGWELE_MOBILE_MONEY_ERROR]',requested,error?.code,String(error?.message||''));return res.status(status>=400&&status<600?status:500).json({success:false,status:'failed',provider:requested,error:String(error?.message||'Erreur Mobile Money.'),code:clean(error?.code||'MOBILE_MONEY_ERROR',80)})}}

export function installMobileMoneyLivePaymentProxy(){const expressAny=express as any;if(expressAny[INSTALL_FLAG])return;expressAny[INSTALL_FLAG]=true;const originalUse=(express.application as any).use;(express.application as any).use=function patchedUse(this:any,...args:any[]){const result=originalUse.apply(this,args);if(!this[APP_FLAG]){this[APP_FLAG]=true;this.get('/api/mobile-money/status',(_req:express.Request,res:express.Response)=>{const mpesa=getMpesaLivePublicStatus();res.json({mode:'production',currency:mpesa.currency||'USD',country:mpesa.country||'CD',providers:{mpesa:{enabled:true,configured:mpesa.configured,label:'M-Pesa'},airtel:{enabled:true,configured:genericConfigured('airtel'),label:'Airtel Money'},orange:{enabled:true,configured:genericConfigured('orange'),label:'Orange Money'},afrimoney:{enabled:true,configured:genericConfigured('afrimoney'),label:'Afrimoney'}}})});this.post('/api/mobile-money/:provider/pay',paymentHandler);this.post('/api/mobile-money/mpesa/c2b',(req:express.Request,res:express.Response)=>{req.params.provider='mpesa';return paymentHandler(req,res)});}return result;};}
